version: '3.8'
services:
  consumer:
    build:
      context: ./
      dockerfile: ./consumer/Dockerfile
    environment:
      - CONSUMER_PROFILES_ACTIVE=${CONSUMER_PROFILES_ACTIVE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SERVICE_USER_NAME=${SERVICE_USER_NAME}
      - SERVICE_USER_SECRET=${SERVICE_USER_SECRET}
      - DB_NAME=${DB_NAME}
      - BOOSTRAP_SERVER_HOST=${BOOSTRAP_SERVER_HOST}
      - BOOSTRAP_SERVER_PORT=${BOOSTRAP_SERVER_PORT}
      - BLOCKS_TOPIC=${BLOCKS_TOPIC}
      - SCHEMA=${SCHEMA}
      - LOG=${LOG}
      - BLOCKS_BATCH_SIZE=${BLOCKS_BATCH_SIZE}
      - COMMIT_THRESHOLD=${COMMIT_THRESHOLD}
      - JDBC_BATCH_SIZE=${JDBC_BATCH_SIZE}
      - MAXIMUM_POOL_SIZE=${MAXIMUM_POOL_SIZE}
      - LIQUIBASE_ENABLE=${LIQUIBASE_ENABLE}
      - SUBMIT_API_CONFIG_URL=${SUBMIT_API_CONFIG_URL}
      - BYRON_GENESIS_URL=${BYRON_GENESIS_URL}
      - SHELLEY_GENESIS_URL=${SHELLEY_GENESIS_URL}
      - ALONZO_GENESIS_URL=${ALONZO_GENESIS_URL}
      - CONWAY_GENESIS_URL=${CONWAY_GENESIS_URL}
      - REDIS_STANDALONE_PORT=${REDIS_STANDALONE_PORT}

networks:
  default:
    name: cardano-rosetta-java
