services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    volumes:
      - ${CARDANO_NODE_DIR}:/ipc/
      - ${CARDANO_NODE_DB}:/node/db
      - ${CARDANO_CONFIG}:/config
    restart: unless-stopped
    ports:
      - ${CARDANO_NODE_PORT}:${CARDANO_NODE_PORT}
    entrypoint: cardano-node run --database-path /node/db --port ${CARDANO_NODE_PORT} --socket-path /ipc/node.socket --topology /config/topology.json --config /config/config.json
    # entrypoint: sleep 3600
  cardano-submit-api:
    image: ghcr.io/intersectmbo/cardano-submit-api:${CARDANO_NODE_VERSION}
    environment:
      - NETWORK=${NETWORK}
    depends_on:
      - cardano-node
    # entrypoint: sleep 3600
    # entrypoint: [
    #   /nix/store/79fw2gwr6sc1m9jrpd82cv3043826rji-cardano-submit-api-exe-cardano-submit-api-10.1.0/bin/cardano-submit-api
    #   --port 8090
    #   --socket-path /ipc/node.socket
    #   --config /config/submit-api-config.yaml
    #   --testnet-magic 3311
    #   --listen-address 0.0.0.0
    # ]
    entrypoint: >-
      /nix/store/79fw2gwr6sc1m9jrpd82cv3043826rji-cardano-submit-api-exe-cardano-submit-api-10.1.0/bin/cardano-submit-api
      --port 8090
      --socket-path /ipc/node.socket
      --config /config/submit-api-config.yaml
      --testnet-magic 3311
      --listen-address 0.0.0.0
    volumes:
      - ${CARDANO_NODE_DIR}:/ipc
      - ${CARDANO_CONFIG}:/config
    ports:
      - ${NODE_SUBMIT_API_PORT}:8090
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


networks:
  default:
    name: cardano-rosetta-java-${NETWORK}
