server:
  port: 8085
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024

spring:
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 16MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: cardano-master
    password: postgres_master_pw
    url: jdbc:postgresql://172.16.1.217:54322/explorer?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&autoReconnect=true&currentSchema=preprod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: false

api:
  exception:
    isPrintStackTrace : true



cardano:
  rosetta:
    version:
      ${ROSETTA_VERSION}
    implementation-version:
      '@project.version@'
    networks:
      [
        {
          id:
            mainnet,
          node-version:
            cardano node 1.30.1,
          indexer:
            {
              type:
                ledgersync,
              endpoint-url:
                http://localhost:8080
            },
          node-bridge:
            {
              type:
                ledgersync,
              endpoint-url:
                http://localhost:8080
            }
        },
        {
          id:
            preprod,
          protocol-magic: 1,
          node-version:
            cardano node 1.30.1,
          indexer:
            {
              type:
                ledgersync,
              endpoint-url:
                http://localhost:8080
            },
          node-bridge:
            {
              type:
                ledgersync,
              endpoint-url:
                http://localhost:8080
            }
        },
        {
          id:
            preview,
          protocol-magic: 2,
          node-version:
            cardano node 1.30.1,
          indexer:
            {
              type:
                ledgersync,
              endpoint-url:
                http://localhost:8080
            },
          node-bridge:
            {
              type:
                ledgersync,
              endpoint-url:
                http://localhost:8080
            }
        }

      ]
    TOPOLOGY_FILEPATH: network-config/network/${NETWORK:preprod}/cardano-node/topology.json
    GENESIS_SHELLEY_PATH: network-config/network/${NETWORK:preprod}/genesis/shelley.json
    CARDANO_NODE_PATH: ${CARDANO_NODE_PATH:/home/lamhoang/Workspace/cardano-node-8.0.0-linux/cardano-node}
    EXEMPTION_TYPES_PATH: network-config/network/exemptions.json


cardano-transaction-submitter:
  connection:
    socket:
      path: ${SUBMIT_SOCKET_CONNECTION:/home/sotatek/Desktop/node-ipc/node.socket}

  networkMagic: ${NETWORK_MAGIC:1}

  transaction:
    ttl: ${TRANSACTION_TTL:3000}
