version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER_TEST:-postgres}
      POSTGRES_PASSWORD: ${DB_SECRET_TEST:-123456}
      POSTGRES_DB: ${DB_NAME_TEST:-test}
    ports:
      - "${DB_PORT_TEST:-5437}:5432"
  cardano-node:
    image: inputoutput/cardano-node
    environment:
      NETWORK: ${SCHEMA:-preprod}
      CARDANO_NODE_SOCKET_PATH: /ipc/node.socket
    volumes:
      - ./node-ipc:/ipc
    restart: "no"
    ports:
      - "3001:3001"
    healthcheck:
      # Ping the EKG port to see if it responds.
      # Assuming if EKG isn't up then the rest of cardano-node isn't either.
      test: [ "CMD-SHELL", "curl -f 127.0.0.1:12788 || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    name: cardano-rosetta-java